### ISSUE TITLE
Missing doc link

### ISSUE THREAD

**Issue by dpsanders** [Datseris/DynamicalBilliards.jl#1]
The link to the docs in the README is missing.

**Comment by Datseris** [comment]
Yes, unfortunately I have not yet learned how I can create external docs ... :( So far I have detailed docstrings everywhere though. I plan to do that after I implement and upload the ray-splitting stuff, probably next week. I haven't submitted to METADATA yet so I have a bit more time.

**Comment by dpsanders** [comment]
Ah OK, no problem. You basically just follow the instructions at https://github.com/JuliaDocs/Documenter.jl,  but ignore all the stuff about `mkdocs`, which is no longer needed.
I went through this process recently so can help if you have any problems. It's actually not too difficult, but there are a couple of slightly fiddly things.

**Comment by Datseris** [comment]
All docs are up and running!

**Comment by dpsanders** [comment]
👍  Looking good!
