### ISSUE TITLE
`billiard_polygon` with periodic conditions does not work adequately

### ISSUE THREAD

**Issue by dapias** [Datseris/DynamicalBilliards.jl#18]
Hello. I have found that this piece of code does not work adequately
```julia
using Dynamical Billiards
a = 1.0
b = 3.0
bt = billiard_polygon(6, b; setting = "periodic")
disc = Disk([0., 0.], a)
push!(bt, disc)
p = randominside(bt)
t = 5
ts, pos, vel = evolve!(p, bt, t)
```
And the reason is that when we create the normal vector as
```julia
normal = inr*normalize([-w[2], w[1]])
```
defined in the function `billiard_polygon` (line 151 of **StandardBilliards.jl**), the `periodicity!` function updates the position of the particle wrongly as `w.normal` is normalized. What I have tried to fix the problem is to change that line by
```julia
normal = normalize([-w[2], w[1]])*sqrt(3)*r
```
As `$sqrt(3) \times r$` is the distance between any two parallel sides of a hexagon. The new problem is that this just works for a triangular billiard (hexagonal unit cell). As the function `billiard_polygon` works only for $4$ or $6$ sides (by mathematical reasons) and the square case works correctly, I propose to implement a specific function for the triangular lattice.

Additionally, a specific function for plotting this kind of unit cell needs to be implemented as the existing function does not translate correctly the scatterers when the periodicity is along non-coordinate vectors. I have made some code for the case discussed here but we could consider to open another issue after solving this one.

**Comment by Datseris** [comment]
Hi Diego,
unfortunately you are correct... periodic doesn't work for `n=6` for exactly the reason you said. But isn't it straightforward to do the condition:
```julia
if n==6 && setting == "periodic"
  normal = normalize([-w[2], w[1]])*sqrt(3)*r
else
  normal = inr*normalize([-w[2], w[1]])
end
```
? What would the new function do differently? 

Also you are right about the plotting: it only works from orthogonal vectors :( 
A new function has to be made for triangular/hexagonal periodicity as far as plotting is concerned...

**Comment by Datseris** [comment]
Also, are you using this package? What are you working on? I am very curious and also very happythat somebody else is using this package!

**Comment by Datseris** [comment]
Hm, also, I just took a much closer look at the source code there. I think the only problem is that I use 
`normal = inr*normalize([-w[2], w[1]])` instead of `normal = 2inr*normalize([-w[2], w[1]])` (notice the 2). Since two opposite faces have distance of twice the inner radius, shouldn't this fix all problems? (besides plotting)

**Comment by dapias** [comment]
Hi there! Oh, you are right.: it seems than `normal = 2.0*inr*normalize([-w[2], w[1]])` fix the problem. 

I am using the package to calculate the spectrum of Lyapunov exponents in Billiards. Just changing few things in the main code it seems very suitable for this purpose. 

I take this chance to thank you for sharing the package :)

**Comment by Datseris** [comment]
yeap we can close this. I just did a commit that changed it to `2inr`.
