### ISSUE TITLE
Help on plotting the trajectory and phase space for elliptical billiard

### ISSUE THREAD

**Issue by pedroLoureiroB** [Datseris/DynamicalBilliards.jl#207]
Hello!  I would like to plot the trajectory and the phase space for the elliptical billiard (the regular one, without obstacles inside or anything like that), but I'm having some trouble, I keep getting this MethodError, which them all say the method I'm trying to use doesn't match the ellipse, eg, MethodError: no method matching randominside(::Ellipse{Float64}). I'm kinda new to programming, so  I'm probably messing some stuff up, can someone help me?

**Comment by Datseris** [comment]
Please provide a **minimal working example** (what's the code you are running that gives this error), provide the full error stack trace, and also provide the versions of the software you use. I would advice to use the New Issue template fully.

**Comment by pedroLoureiroB** [comment]
First of all, I'm using version 4.1.0 of DynamicalBilliards, and Julia version 1.10

The code is:
`using DynamicalBilliards
bd = Ellipse([0,0],2.0,1.0)

particle = randominside(bd)` 

The error I get is:
<img width="891" alt="Error" src="https://github.com/user-attachments/assets/bf9b5ede-3170-4c29-a6e4-3205d9ccbadd">

**Comment by Datseris** [comment]
`bd` is not a billiard. Try `e = Ellipse(...)` and then `bd = Billiard((e, ))` .

**Comment by pedroLoureiroB** [comment]
That worked! I really don't know how to thank you properly, man, thank you so much!

**Comment by Datseris** [comment]
just go trhough this page carefully and you should learn everything well: https://juliadynamics.github.io/DynamicalBilliards.jl/stable/basic/high_level/
