### ISSUE TITLE
AppVeyor tests?

### ISSUE THREAD

**Issue by ChrisRackauckas** [Datseris/DynamicalBilliards.jl#8]
Is it setup? There's no badge.

**Comment by Datseris** [comment]
Yes AppVeyor tests are fully operation and passing perfectly!
Where can I find the badge?

**Comment by ChrisRackauckas** [comment]
If you got to settings, there's a section for badges. Get the Markdown one and just plop it in there.

**Comment by Datseris** [comment]
Okay badge is green and passing
